In [1]:
import pandas as pd
import os

In [2]:
file = os.path.join("InternationalGDP.csv")

# The correct encoding must be used to read the CSV in pandas
df = pd.read_csv(file, encoding="ISO-8859-1")

In [4]:
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.390503e+09,2.549721e+09,2.534637e+09,2.581564e+09,2.649721e+09,2.691620e+09,2.646927e+09,2.700559e+09,NaN,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,1.585657e+10,1.780428e+10,2.000162e+10,2.056105e+10,2.048487e+10,1.990711e+10,1.936264e+10,2.019176e+10,1.936297e+10,NaN
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.379950e+10,1.117900e+11,1.280530e+11,1.367100e+11,1.457120e+11,1.161940e+11,1.011240e+11,1.221240e+11,1.057510e+11,NaN
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.192696e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.138693e+10,1.186135e+10,1.302506e+10,1.510250e+10,NaN
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.013387e+09,3.236544e+09,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.830416e+09,6.692431e+09,6.499760e+09,7.071982e+09,7.386883e+09,6.440068e+09,6.714727e+09,7.227700e+09,7.938991e+09,NaN
260,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.090675e+10,3.272642e+10,3.540134e+10,4.041523e+10,4.322859e+10,4.262833e+10,3.096824e+10,2.681870e+10,2.691440e+10,NaN
261,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,7.575397e+09,7.972997e+09,8.497997e+09,9.423396e+09,1.037400e+10,1.133440e+10,...,3.753490e+11,4.164190e+11,3.963330e+11,3.668290e+11,3.509050e+11,3.176210e+11,2.963570e+11,3.495540e+11,3.682890e+11,NaN
262,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.124335e+10,2.095475e+10,2.586814e+10,2.672007e+10,NaN
263,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,1.204166e+10,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,2.281301e+10,3.100052e+10,NaN

In [5]:
# setting column Country as index"
df.set_index("Country Name", inplace=True)
df

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.390503e+09,2.549721e+09,2.534637e+09,2.581564e+09,2.649721e+09,2.691620e+09,2.646927e+09,2.700559e+09,NaN,NaN
Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,...,1.585657e+10,1.780428e+10,2.000162e+10,2.056105e+10,2.048487e+10,1.990711e+10,1.936264e+10,2.019176e+10,1.936297e+10,NaN
Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.379950e+10,1.117900e+11,1.280530e+11,1.367100e+11,1.457120e+11,1.161940e+11,1.011240e+11,1.221240e+11,1.057510e+11,NaN
Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.192696e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.138693e+10,1.186135e+10,1.302506e+10,1.510250e+10,NaN
Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.013387e+09,3.236544e+09,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.830416e+09,6.692431e+09,6.499760e+09,7.071982e+09,7.386883e+09,6.440068e+09,6.714727e+09,7.227700e+09,7.938991e+09,NaN
"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.090675e+10,3.272642e+10,3.540134e+10,4.041523e+10,4.322859e+10,4.262833e+10,3.096824e+10,2.681870e+10,2.691440e+10,NaN
South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,7.575397e+09,7.972997e+09,8.497997e+09,9.423396e+09,1.037400e+10,1.133440e+10,1.235500e+10,...,3.753490e+11,4.164190e+11,3.963330e+11,3.668290e+11,3.509050e+11,3.176210e+11,2.963570e+11,3.495540e+11,3.682890e+11,NaN
Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,...,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.124335e+10,2.095475e+10,2.586814e+10,2.672007e+10,NaN
Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,...,1.204166e+10,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,2.281301e+10,3.100052e+10,NaN

In [6]:
# selecting desired columns"
df_yrs=df[["Country Code","Indicator Name", "1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006", "2007","2008", "2009","2010","2011","2012", "2013","2014","2015","2016","2017"]]
df_yrs

,Country Code,Indicator Name,1995,1996,1997,1998,1999,2000,2001,2002,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,GDP (current US$),1.320475e+09,1.379961e+09,1.531944e+09,1.665101e+09,1.722799e+09,1.873453e+09,1.920112e+09,1.941341e+09,...,2.745251e+09,2.498883e+09,2.390503e+09,2.549721e+09,2.534637e+09,2.581564e+09,2.649721e+09,2.691620e+09,2.646927e+09,2.700559e+09
Afghanistan,AFG,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.055177e+09,...,1.010922e+10,1.243909e+10,1.585657e+10,1.780428e+10,2.000162e+10,2.056105e+10,2.048487e+10,1.990711e+10,1.936264e+10,2.019176e+10
Angola,AGO,GDP (current US$),5.538749e+09,7.526447e+09,7.648377e+09,6.506230e+09,6.152923e+09,9.129595e+09,8.936064e+09,1.528559e+10,...,8.853861e+10,7.030716e+10,8.379950e+10,1.117900e+11,1.280530e+11,1.367100e+11,1.457120e+11,1.161940e+11,1.011240e+11,1.221240e+11
Albania,ALB,GDP (current US$),2.392765e+09,3.199643e+09,2.258516e+09,2.545967e+09,3.212119e+09,3.480355e+09,3.922099e+09,4.348070e+09,...,1.288135e+10,1.204422e+10,1.192696e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.138693e+10,1.186135e+10,1.302506e+10
Andorra,AND,GDP (current US$),1.178739e+09,1.223945e+09,1.180597e+09,1.211932e+09,1.239876e+09,1.434430e+09,1.496913e+09,1.733117e+09,...,4.007353e+09,3.660531e+09,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.013387e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,XKX,GDP (current US$),NaN,NaN,NaN,NaN,NaN,1.849196e+09,2.535334e+09,2.406271e+09,...,5.687362e+09,5.653823e+09,5.830416e+09,6.692431e+09,6.499760e+09,7.071982e+09,7.386883e+09,6.440068e+09,6.714727e+09,7.227700e+09
"Yemen, Rep.",YEM,GDP (current US$),4.258789e+09,5.785685e+09,6.838557e+09,6.325142e+09,7.641103e+09,9.652436e+09,9.861560e+09,1.069463e+10,...,2.691085e+10,2.513027e+10,3.090675e+10,3.272642e+10,3.540134e+10,4.041523e+10,4.322859e+10,4.262833e+10,3.096824e+10,2.681870e+10
South Africa,ZAF,GDP (current US$),1.554610e+11,1.476060e+11,1.525870e+11,1.377750e+11,1.366320e+11,1.363610e+11,1.215150e+11,1.154820e+11,...,2.867700e+11,2.959360e+11,3.753490e+11,4.164190e+11,3.963330e+11,3.668290e+11,3.509050e+11,3.176210e+11,2.963570e+11,3.495540e+11
Zambia,ZMB,GDP (current US$),3.807067e+09,3.597221e+09,4.303282e+09,3.537683e+09,3.404312e+09,3.600683e+09,4.094481e+09,4.193846e+09,...,1.791086e+10,1.532834e+10,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.124335e+10,2.095475e+10,2.586814e+10
Zimbabwe,ZWE,GDP (current US$),7.111271e+09,8.553147e+09,8.529572e+09,6.401968e+09,6.858013e+09,6.689958e+09,6.777385e+09,6.342116e+09,...,4.415703e+09,9.665793e+09,1.204166e+10,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,2.281301e+10

In [10]:
df_yrs.count()

Country Code      264
Indicator Name    264
1995              234
1996              234
1997              234
1998              236
1999              237
2000              244
2001              244
2002              249
2003              249
2004              250
2005              251
2006              251
2007              252
2008              251
2009              251
2010              251
2011              252
2012              251
2013              253
2014              252
2015              251
2016              250
2017              247
dtype: int64

In [14]:
df_clean = df_yrs.fillna(0)
df_clean

,Country Code,Indicator Name,1995,1996,1997,1998,1999,2000,2001,2002,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,GDP (current US$),1.320475e+09,1.379961e+09,1.531944e+09,1.665101e+09,1.722799e+09,1.873453e+09,1.920112e+09,1.941341e+09,...,2.745251e+09,2.498883e+09,2.390503e+09,2.549721e+09,2.534637e+09,2.581564e+09,2.649721e+09,2.691620e+09,2.646927e+09,2.700559e+09
Afghanistan,AFG,GDP (current US$),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.055177e+09,...,1.010922e+10,1.243909e+10,1.585657e+10,1.780428e+10,2.000162e+10,2.056105e+10,2.048487e+10,1.990711e+10,1.936264e+10,2.019176e+10
Angola,AGO,GDP (current US$),5.538749e+09,7.526447e+09,7.648377e+09,6.506230e+09,6.152923e+09,9.129595e+09,8.936064e+09,1.528559e+10,...,8.853861e+10,7.030716e+10,8.379950e+10,1.117900e+11,1.280530e+11,1.367100e+11,1.457120e+11,1.161940e+11,1.011240e+11,1.221240e+11
Albania,ALB,GDP (current US$),2.392765e+09,3.199643e+09,2.258516e+09,2.545967e+09,3.212119e+09,3.480355e+09,3.922099e+09,4.348070e+09,...,1.288135e+10,1.204422e+10,1.192696e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.138693e+10,1.186135e+10,1.302506e+10
Andorra,AND,GDP (current US$),1.178739e+09,1.223945e+09,1.180597e+09,1.211932e+09,1.239876e+09,1.434430e+09,1.496913e+09,1.733117e+09,...,4.007353e+09,3.660531e+09,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.013387e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,XKX,GDP (current US$),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.849196e+09,2.535334e+09,2.406271e+09,...,5.687362e+09,5.653823e+09,5.830416e+09,6.692431e+09,6.499760e+09,7.071982e+09,7.386883e+09,6.440068e+09,6.714727e+09,7.227700e+09
"Yemen, Rep.",YEM,GDP (current US$),4.258789e+09,5.785685e+09,6.838557e+09,6.325142e+09,7.641103e+09,9.652436e+09,9.861560e+09,1.069463e+10,...,2.691085e+10,2.513027e+10,3.090675e+10,3.272642e+10,3.540134e+10,4.041523e+10,4.322859e+10,4.262833e+10,3.096824e+10,2.681870e+10
South Africa,ZAF,GDP (current US$),1.554610e+11,1.476060e+11,1.525870e+11,1.377750e+11,1.366320e+11,1.363610e+11,1.215150e+11,1.154820e+11,...,2.867700e+11,2.959360e+11,3.753490e+11,4.164190e+11,3.963330e+11,3.668290e+11,3.509050e+11,3.176210e+11,2.963570e+11,3.495540e+11
Zambia,ZMB,GDP (current US$),3.807067e+09,3.597221e+09,4.303282e+09,3.537683e+09,3.404312e+09,3.600683e+09,4.094481e+09,4.193846e+09,...,1.791086e+10,1.532834e+10,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.124335e+10,2.095475e+10,2.586814e+10
Zimbabwe,ZWE,GDP (current US$),7.111271e+09,8.553147e+09,8.529572e+09,6.401968e+09,6.858013e+09,6.689958e+09,6.777385e+09,6.342116e+09,...,4.415703e+09,9.665793e+09,1.204166e+10,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,2.281301e+10

In [15]:
#Saving Output
output_file = os.path.join("Clean_InterGDP.csv")

df_clean.to_csv(output_file, index=False, header=True)